apiVersion: v1
kind: Service
metadata:
    name: codesnippets-service
spec:
    selector:
        app: codesnippets    
    ports:
    - protocol: TCP
        port: 3000
        targetPort: 3000
    type: ClusterIP